learning_log/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
    url(r'^markdownx/', include('markdownx.urls')),
]

learning_logs/urls.py
"""Defines URL patters for learning_logs."""

from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^topics/$', views.topics, name='topics'),
        url(r'^new_topic/$', views.new_topic, name='new_topic'),
        url(r'^edit_topic/(?P<topic_id>\d+)$', views.edit_topic, name='edit_topic'),
        url(r'topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
        url(r'new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
        url(r'edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
        url(r'delete_entry/(?P<entry_id>\d+)/$', views.delete_entry, name='delete_entry')
    ]

users/urls.py
""" Defines URL patters for users"""

from django.conf.urls import url
from django.contrib.auth.views import login


from . import views

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^demo/$', login, {'template_name': 'users/demo.html'}, name='demo'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from django.contrib.auth.models import User
from django.db import models
from markdownx.models import MarkdownxField


class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        """Return a string representation of the model"""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic)
    markdown_field = MarkdownxField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

users/models.py
from django.db import models

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['markdown_field']

learning_logs/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from markdownx.utils import markdownify

from .forms import TopicForm, EntryForm
from .models import Topic, Entry


def index(request):
    """Home page for Learning Log"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Show all topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required()
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = get_object_or_404(Topic, id=topic_id)
    # Make sure teh topic belongs to the current user
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    # Show rendered markdown in entries list
    # https://github.com/adi-/django-markdownx/issues/25#issuecomment-230315833
    for entry in entries:
        entry.markdown_field = markdownify(entry.markdown_field)
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required()
def new_topic(request):
    """Add new topic"""
    if request.method != 'POST':
        form = TopicForm()
    else:
        # POST data submitted process data
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required()
def edit_topic(request, topic_id):
    """Edit topic name"""
    topic = get_object_or_404(Topic, id=topic_id)
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = TopicForm(instance=topic)
    else:
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_topic.html', context)


@login_required()
def new_entry(request, topic_id):
    """Add new entry for a particular topic"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # No data submitted, create a blank form
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


# todo delete entry
@login_required()
def delete_entry(request, entry_id):
   entry = Entry.objects.get(id=entry_id)
   if entry.topic.owner != request.user:
       raise Http404
   else:
       entry.delete()

   return render(request, 'learning_logs/topic.html')

@login_required()
def edit_entry(request, entry_id):
    """Edit and existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # Initial request, pre fill with the current entry
        form = EntryForm(instance=entry)
    else:
        # POST data submitted, process data
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render


def logout_view(request):
    """lOg the user out"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


# todo Extend registration form
def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Display blank registration form
        form = UserCreationForm()
    else:
        # Process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log in the user and redirect to homepage
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_log/templates/markdownx/widget.html
<div class="markdownx row">
    <div class="col-md-6">
        {{ markdownx_editor }}
    </div>
    <div class="col-md-6">
        <div class="markdownx-preview"></div>
    </div>
</div>

learning_logs/templates/learning_logs/base.html
{# Load the collection of template tags provided by django-bootstrap #}
{% load bootstrap3 %}
{% load static %}
{% load staticfiles %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0">
    <title>Learning Log</title>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            console.log("ready");

            $('.markdownx').on('markdownx.init', function () {
                console.log("INIT");
            });

            $('.markdownx').on('markdownx.update', function (e, response) {
                console.log("UPDATE" + response);
            });
        });
    </script>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link rel="stylesheet"
          href="{% static "learning_logs/css/font-awesome.min.css" %}">
</head>
<body>
{# Static navbar #}
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span><span
                    class="icon-bar"></span><span class="icon-bar"></span>
            </button>
            {% if user.is_authenticated %}
                <a href="{% url 'learning_logs:topics' %}"
                   class="navbar-brand">Topics</a>
            {% else %}
                <a href="{% url 'learning_logs:index' %}" class="navbar-brand">
                    Leaning Log
                </a>
            {% endif %}
        </div>

        <div class="navbar-collapse collapse" id="navbar">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="https://github.com/sfarzy/learning_log.git"><i
                        class="fa fa-github fa-2x" aria-hidden="true"></i></a>
                </li>
                {% if user.is_authenticated %}
                    <li><a>Hello, {{ user.username }}</a></li>
                    <li><a href="{% url 'users:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'users:demo' %}">Demo</a></li>
                    <li><a href="{% url 'users:register' %}">Register</a></li>
                    <li><a href="{% url 'users:login' %}">Log in</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</div>

</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{%  extends 'learning_logs/base.html' %}

{% block header %}
     <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> - Edit Entry</h3>
{% endblock %}

{% block content %}

    <form action="{%  url 'learning_logs:edit_entry' entry.id %}" method="post">
        {%  csrf_token %}
        {{ form.as_p }}
        <button name="submit" class='btn btn-primary'>Save Changes</button>
        <a href={% url 'learning_logs:topics' %} class='btn btn-danger'>Cancel</a>
    </form>
    {{ form.media }}
{% endblock content %}

learning_logs/templates/learning_logs/edit_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Edit Topic</h2>
{% endblock %}

{% block content %}
    <form action="{% url 'learning_logs:edit_topic' topic.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="{% url 'learning_logs:topics' %}" class='btn btn-danger'>Cancel</a>
        {% endbuttons %}
    </form>
{% endblock %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1>Track your learning.</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">Register an account</a> to make your own Leaning log and list the topics you're learning about.
    </h2>
    <h2>
        Whenever you learn something new about a topic, make an entry summating what you've learned.
    </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> - New Entry</h2>
{% endblock %}

{% block content %}
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {%  csrf_token %}
        {{ form.as_p }}
        <button name='submit' class='btn btn-primary'>Save</button>
        <a href="{% url 'learning_logs:topics' %}" class='btn btn-danger'>Cancel</a>
    </form>
    {{ form.media }}
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{%  extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method='post'>
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class=""btn btn-primary>Add topic</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>{{ topic }}</h2>
    <a class="btn btn-default"
       href="{% url 'learning_logs:edit_topic' topic.id %}">Edit Topic</a>
{% endblock %}

{% block content %}

    <h3> Entries </h3>
    <a class="btn btn-success"
       href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
    </p>
    <ul>
        {% for entry in entries %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>
                        {{ entry.date_added|date:'M d, Y H:i' }}
                        <small>
                            <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                                Edit entry
                            </a>
                            <a href="{% url 'learning_logs:delete_entry' entry.id %}">
                                Delete Entry
                            </a>
                        </small>
                    </h3>
                </div>
                <div class="panel-body">
                    {{ entry.markdown_field|safe }}
                </div>
            </div>
        {% empty %}
            There are no entries for this topic yet.
        {% endfor %}
    </ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <h1>Topics</h1>
{% endblock header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <h3><a href={% url 'learning_logs:topic' topic.id  %}>{{ topic }} </a></h3>
            </li>
        {% empty %}
            <li> No topics have been added yet.</li>
        {% endfor %}
    </ul>
    <a class="btn btn-success" href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>
{% endblock content %}

users/templates/users/demo.html
{%  extends "learning_logs/base.html" %}
{%  load bootstrap3 %}

{% block header %}
    <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
    <p>Use <code><strong>username</strong> : demo</code> and <code><strong>password</strong> : abcd12345</code></p>
    <form action="{% url 'users:demo' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit">Log In</button>
        {% endbuttons %}
        {# Specify where to redirect if the user is logged in #}
        <input type="hidden" name="next" value="{% url 'learning_logs:topics' %}" />
    </form>

{% endblock content %}

users/templates/users/login.html
{%  extends "learning_logs/base.html" %}
{%  load bootstrap3 %}

{% block header %}
    <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit">Log In</button>
        {% endbuttons %}
        {# Specify where to redirect if the user is logged in #}
        <input type="hidden" name="next" value="{% url 'learning_logs:topics' %}" />
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block content %}
    <form action="{% url 'users:register' %}" method="post">
        {%  csrf_token %}
        {% bootstrap_form form %}
        <button name="submit">Register</button>
        <input type="hidden" name="next" value="{% url 'learning_logs:topics' %}" />
    </form>
{% endblock content %}